# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: '@SyliusPriceHistoryPlugin/config/events.yaml' }
    - { resource: '@SyliusPriceHistoryPlugin/config/grids/*' }
        
framework:
    messenger:
        buses:
            sylius.no_transaction_command_bus:
                middleware:
                    - 'validation'
