# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: '@SyliusPriceHistoryPlugin/config/events.yaml' }
    - { resource: '@SyliusPriceHistoryPlugin/config/grids/*' }
