# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: '@SyliusPriceHistoryPlugin/config/events.yaml' }
    - { resource: '@SyliusPriceHistoryPlugin/config/grids/*' }

sylius_core:
    resources:
        channel_pricing:
            classes:
                repository: Sylius\PriceHistoryPlugin\Infrastructure\Doctrine\ORM\ChannelPricingRepository
